#!/bin/bash

if [ ! -f /root/client.ovpn ]
then
	cat << EOF


It's the first boot, we are crafting your keys,
this is going to take a long time... ~30m since the boot

You can display the progressing or the path to your config file with:
	-- oc-check-vpn

EOF
else
	oc-check-vpn
fi

